name: regression
on:
  workflow_dispatch: {}
  push: { branches: [main] }
permissions:
  contents: read
concurrency:
  group: regression-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Descargar APK de stg-latest
        uses: robinraju/release-downloader@v1
        with:
          repository: ${{ github.repository }}
          tag: stg-latest
          fileName: "*.apk"
          out-file-path: dist
      - name: Publicar artifact APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-staging
          path: dist/*.apk

  regression:
    needs: get-apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Descargar APK
        uses: actions/download-artifact@v4
        with:
          name: apk-staging
          path: dist

      - name: Java (requerido por Android tools)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: SDK de Android
        uses: android-actions/setup-android@v3

      - name: Node para Appium
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Python y dependencias
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          pip install -r requirements.txt || true
          pip install appium-python-client behave allure-behave

      # Mantener TODO dentro de este paso para que el emulador siga vivo
      - name: Emulador + instalar APK + correr regresión
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          emulator-options: -no-window -no-audio -gpu swiftshader_indirect
          script: |
            adb install -r dist/*.apk
            npx appium --base-path /wd/hub & sleep 8
            behave -t @regression -q || behave -q

      - name: Subir Allure (si existe)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
